# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = false

[username]
disabled = true

[hostname]
disabled = true

[directory]
truncation_length = 3
truncate_to_repo = false # If in a git repo, truncates the path to the root dir of the git repo
truncation_symbol = '.../'
style = "bold italic blue"
# read_only = ' ğŸ”’'
read_only = ' ğŸ”'
read_only_style = 'purple'

[git_branch]
symbol = "ï˜ "
# format = '[$symbol $branch](purple)'

[character]
success_symbol = '[â®](bold purple)'
error_symbol = '[âœ—](bold red)'

# Make prompt single line
[line_break]
disabled = true

[package]
disabled = true
